name: Run golangci-lint

on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: 'true'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-
                
      - name: Format
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "Code is not formatted properly"
            exit 1
          fi

      - name: Go mod tidy
        run: go mod tidy

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54

      - name: Run golangci-lint
        run: golangci-lint run
